### PR TITLE
Development

### PR DESCRIPTION
**Pull request by mcrd25**

### CODE REVIEW

**Comment by talihomz** [comment]
Hi @mcrd25 @adriaanbd.

Great work implementing MicroReddit!! I was able to build and run the project on my PC.
The code looks as well! (Though there might be some syntax errors, as reported by [Stickler](https://github.com/mcrd25/micro-reddit/pull/3/checks?check_run_id=110062659) )

However, there is one validation that might be troublesome. The suspect is the [password digest validation in your User model](https://github.com/mcrd25/micro-reddit/blob/3257d63beadbca2bf9c40198b442856d4f6e3b44/app/models/user.rb#L17). Its not optimal to create a validation for this, especially a length based one, since different passwords create different hashes. (`test123` creates a length of 50!)
validation
Change this, as just a password and password confirmation validation is fine.

In any case, great job implementing validations in your models!

**Comment by mcrd25** [comment]
Hi @talihomz , thanks for the review, we've really been waiting for it! 😃 

Thanks, we would implement change do you wish for us to submit another review?

As for the stickler, we actually don't know why it threw the errors 😕 since it's referencing rails generated code but we would check it out again. 

Thanks for the review again!

**Comment by talihomz** [comment]
Yes please do submit another request!

I've noticed that Stickler has some issues on a couple of repos. The code reviews team is currently trying to get to the bottom of it.

**Comment by talihomz** [comment]
Hi @mcrd25 @adriaanbd.

The changes have been noted! 
Its a :+1: from me.

**Pull request merged**
